project:
  type: website

website:
  title: "Dan Negrey"
  site-url: https://dnegrey.github.io/
  favicon: www/favicon.ico
  description: "This is Dan Negrey's personal blog."
  page-footer:
    center: "Copyright 2023, Dan Negrey"
  navbar:
    pinned: true
    left:
      - index.qmd
      - about.qmd
      - blog.qmd
    right:
      - icon: github
        href: https://github.com/dnegrey
      - icon: linkedin
        href: https://www.linkedin.com/in/dnegrey
      - icon: twitter
        href: https://twitter.com/NegreyDan
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: www/styles.css
