# Leaflet by Example: Election 2000 {.tabset}

*May 05, 2016*

## Article



## Code

### Load necessary packages

```{r}
library(maptools)
library(httr)
library(XML)
library(dplyr)
library(leaflet)
```

### Download U.S. state shape data

```{r}
download.file(
    "http://www2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_us_state_20m.zip",
    "cb_2014_us_state_20m.zip"
)
unzip(
    "cb_2014_us_state_20m.zip",
    exdir = "cb_2014_us_state_20m"
)
```

### Import U.S. state shape data

```{r}
stateMap <- readShapePoly(fn = "cb_2014_us_state_20m/cb_2014_us_state_20m")
```

### Pull election results

```{r}
x <- GET("http://www.fec.gov/pubrec/fe2000/elecpop.htm")
x <- readHTMLTable(rawToChar(x$content), stringsAsFactors = FALSE)
x <- x[[1]]
x <- x[2:(nrow(x) - 1), ]
for (i in 2:7) {
    x[, i] <- as.integer(gsub("[^0-9]", "", x[, i]))
}
names(x) <- c(
    "StateAbbrev",
    "ElectoralBush",
    "ElectoralGore",
    "PopularBush",
    "PopularGore",
    "PopularOther",
    "PopularTotal"
)
x$Winner <- ifelse(is.na(x$ElectoralBush), "Gore", "Bush")
stateResults <- x
rm(x)
```

### Construct Map

```{r}
x <- subset(stateMap, stateMap$STUSPS %in% stateResults$StateAbbrev)
x$StateAbbrev <- as.character(x$STUSPS)
x@data <- x@data %>% 
    inner_join(stateResults, "StateAbbrev")
pal <- colorFactor(palette = c("Red", "Blue"), domain = c("Bush", "Gore"))
leaflet() %>% 
    addProviderTiles("OpenStreetMap.BlackAndWhite") %>% 
    setView(lng = -98.35,
            lat = 39.50,
            zoom = 4) %>% 
    addPolygons(data = x,
                color = "#FFFFFF",
                weight = 2,
                fillColor = ~ pal(Winner),
                fillOpacity = 0.80,
                popup = ~ paste0(
                    "<b>", NAME, "</b>",
                    "<br>", "Abbreviation: ", StateAbbrev
                )) %>% 
    addLegend(position = "bottomleft",
              pal = pal,
              values = c("Bush", "Gore"),
              title =)
```

